const express=require("express");
const bcrypt=require("bcryptjs");
const jwt=require("jsonwebtoken");
const crypto=require("crypto");
const {run,get}=require("../db");
const router=express.Router();
const pub=u=>({id:u.id,name:u.name,email:u.email,createdAt:u.created_at});
function token(u){return jwt.sign({id:u.id,email:u.email},process.env.JWT_SECRET,{expiresIn:"7d"})}
router.post("/register",async(req,res)=>{try{const name=String(req.body.name||"").trim(),email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");if(name.length<2)return res.status(400).json({success:false,message:"Please enter your full name."});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({success:false,message:"Please enter a valid email address."});if(password.length<6)return res.status(400).json({success:false,message:"Password must contain at least 6 characters."});if(await get("SELECT id FROM users WHERE email=?",[email]))return res.status(409).json({success:false,message:"This email is already registered."});const hash=await bcrypt.hash(password,12),r=await run("INSERT INTO users(name,email,password_hash) VALUES(?,?,?)",[name,email,hash]);await run("INSERT INTO settings(user_id) VALUES(?)",[r.id]);const u=await get("SELECT * FROM users WHERE id=?",[r.id]);res.status(201).json({success:true,message:"Account created successfully.",user:pub(u)})}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to create account."})}});
router.post("/login",async(req,res)=>{try{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),u=await get("SELECT * FROM users WHERE email=?",[email]);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({success:false,message:"Invalid email or password."});res.json({success:true,message:"Login successful.",token:token(u),user:pub(u)})}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to login."})}});
router.post("/forgot-password",async(req,res)=>{try{const email=String(req.body.email||"").trim().toLowerCase(),u=await get("SELECT id FROM users WHERE email=?",[email]);if(!u)return res.json({success:true,message:"If that email exists, a reset request has been created."});const t=crypto.randomBytes(32).toString("hex");await run("INSERT INTO password_resets(user_id,token,expires_at) VALUES(?,?,?)",[u.id,t,Date.now()+15*60*1000]);res.json({success:true,message:"Password reset request created.",resetToken:t,expiresInMinutes:15})}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to create password reset request."})}});
router.post("/reset-password",async(req,res)=>{try{const t=String(req.body.token||""),p=String(req.body.newPassword||"");if(p.length<6)return res.status(400).json({success:false,message:"Password must contain at least 6 characters."});const r=await get("SELECT * FROM password_resets WHERE token=? AND used=0 ORDER BY id DESC LIMIT 1",[t]);if(!r||r.expires_at<Date.now())return res.status(400).json({success:false,message:"Reset token is invalid or expired."});const h=await bcrypt.hash(p,12);await run("UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",[h,r.user_id]);await run("UPDATE password_resets SET used=1 WHERE id=?",[r.id]);res.json({success:true,message:"Password reset successfully."})}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to reset password."})}});
module.exports=router;
