require("dotenv").config();
const express=require("express");const cors=require("cors");const {initDatabase}=require("./db");
const app=express();const PORT=Number(process.env.PORT)||5000;const origin=process.env.FRONTEND_URL||"*";
app.use(cors({origin:origin==="*"?true:origin,credentials:true}));app.use(express.json({limit:"1mb"}));
app.get("/",(req,res)=>res.json({success:true,message:"Task Manager API is running.",version:"1.0.0"}));
app.get("/api/health",(req,res)=>res.json({success:true,status:"ok",database:"SQLite"}));
app.use("/api/auth",require("./routes/auth"));app.use("/api/tasks",require("./routes/tasks"));app.use("/api/profile",require("./routes/profile"));app.use("/api/settings",require("./routes/settings"));
app.use((req,res)=>res.status(404).json({success:false,message:"API endpoint not found."}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({success:false,message:"Internal server error."})});
(async()=>{await initDatabase();app.listen(PORT,()=>console.log(`Task Manager API running on http://localhost:${PORT}`))})().catch(e=>{console.error("Server startup failed:",e);process.exit(1)});
